//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientData
    {
        public int Id { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<double> ProfitLoss { get; set; }
        public Nullable<double> TotalCosts { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
