//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costing
    {
        public int Id { get; set; }
        public Nullable<int> Veh { get; set; }
        public Nullable<double> Total_Distance { get; set; }
        public Nullable<double> Total_Fuel_Used { get; set; }
        public Nullable<double> Average_Consumption_Lper100Km { get; set; }
        public Nullable<double> Average_Consumption_MPG { get; set; }
        public Nullable<double> Total_Cost_of_running { get; set; }
        public Nullable<double> Diesel_Cost_per_l { get; set; }
        public Nullable<double> Target_Consumption { get; set; }
        public Nullable<double> AddBlue_Percentage_Per_L { get; set; }
        public Nullable<double> AddBlue_Cost_Per_L { get; set; }
        public Nullable<double> Approximate_Adblue_L { get; set; }
        public Nullable<double> Approximate_Addblue_Cost { get; set; }
        public Nullable<double> Current_Consumption { get; set; }
        public Nullable<double> At_Average_Consumption { get; set; }
        public Nullable<double> At_Best_Consumption { get; set; }
        public Nullable<double> At_Target_Consumption { get; set; }
        public Nullable<double> Diff_AtAv_Total_Fuel_Used_Diff_L { get; set; }
        public Nullable<double> Diff_AtAv_Total_Fuel_Cosy { get; set; }
        public Nullable<double> Diff_AtAv_Fuel_Savings { get; set; }
        public Nullable<double> Diff_AtBst_Total_Fuel_Used_Diff_L { get; set; }
        public Nullable<double> Diff_AtBst_Total_Fuel_Cost { get; set; }
        public Nullable<double> Diff_AtBst_Fuel_Savings { get; set; }
        public Nullable<double> Diff_AtTrgt_Total_Fuel_Used_Diff_L { get; set; }
        public Nullable<double> Diff_AtTrgt_Total_FuelCost { get; set; }
        public Nullable<double> Diff_AtTrgt_Fuel_Savings { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string VehCode { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
