//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRV_Duty
    {
        public int Id { get; set; }
        public Nullable<int> Veh { get; set; }
        public Nullable<int> Drv { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Duty_Start { get; set; }
        public Nullable<System.TimeSpan> Duty_End { get; set; }
        public Nullable<System.TimeSpan> Duty_Time { get; set; }
        public Nullable<double> Total_Km { get; set; }
        public Nullable<double> MPG { get; set; }
        public Nullable<double> Co2_Kg { get; set; }
        public string VehCode { get; set; }
        public string DrvName { get; set; }
        public Nullable<double> C_drivers_Standard_Rate { get; set; }
        public Nullable<double> C_drivers_Overtime_Rate { get; set; }
        public string C_drivers_Employment_Type { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
