//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAN_Data
    {
        public int Id { get; set; }
        public Nullable<int> Veh { get; set; }
        public Nullable<int> Drv { get; set; }
        public Nullable<int> Manifest_Number { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Total_Jobs { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
