//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prg_dataEntities : DbContext
    {
        public prg_dataEntities()
            : base("name=prg_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientData> ClientDatas { get; set; }
        public virtual DbSet<Costing> Costings { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DRV_Duty> DRV_Duty { get; set; }
        public virtual DbSet<MAN_Data> MAN_Data { get; set; }
        public virtual DbSet<Utilisation_Data> Utilisation_Data { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VTRN_Data> VTRN_Data { get; set; }
    }
}
