//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrkWebApp.Diagram_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisation_Data
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Man_Date_Drv { get; set; }
        public Nullable<int> Man_Number { get; set; }
        public Nullable<int> Man_Total_Packs { get; set; }
        public Nullable<int> Man_Total_Jobs { get; set; }
        public string Man_Veh_Code { get; set; }
        public Nullable<int> Bkg_Number { get; set; }
        public string Bkg_Customer_Code { get; set; }
        public Nullable<int> Bkg_Cons_Packs { get; set; }
        public Nullable<int> Bkg_Cons_Weight { get; set; }
        public Nullable<double> Bkg_Cons_Price { get; set; }
        public Nullable<double> Man_Total_Revenue { get; set; }
        public Nullable<int> Veh { get; set; }
        public Nullable<int> Client { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
